resolvedEdits
gcater/bookwyrm pull request #3
Opened 2024-03-26 23:19 UTC by gcater

Took a second to navigate git, but have taken out react-query and the book interface. Same things as before so amended prisma, set google login, and setup a basic book TRPC mutation and query. Will soon change how this works. 

<img width="1512" alt="Screenshot 2024-03-26 at 7 16 44 PM" src="https://github.com/gcater/bookwyrm/assets/109175497/8aac3027-bb71-4214-b368-ea2b21ae436c">

2024-03-26 23:57 UTC, Evanc123 requested changes

2024-03-26 23:57 UTC, Evanc123 commented on src/pages/index.tsx
> +      {data.map((book: any) => (
so this shouldn't be an Any (we should almost never use any), it should come from Book exported by the `trpc` client

2024-03-26 23:58 UTC, Evanc123 commented on src/pages/index.tsx
> +      {data.map((book: any) => (
plz also fix the merge conflicts

2024-03-26 23:58 UTC, Evanc123 commented on src/pages/index.tsx
> +      {data.map((book: any) => (
thanks for the photo! helpful

2024-03-27 00:50 UTC, gcater commented
Fixed some git errors and took the any out

2024-03-27 00:51 UTC, Evanc123 approved these changes

2024-03-27 19:47 UTC, merged